name: "Setup"
description: "Setup Node.js environment and dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"
        cache: "npm"
        cache-dependency-path: "package-lock.json"

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node_modules-${{hashFiles('package-lock.json')}}
        restore-keys: node_modules-
