name: Build and check code quality

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
      - alpha
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  install:
    name: Install package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: "./.github/actions/setup"

  commitlint:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    name: Lint commit messages
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js and install dependencies
        uses: "./.github/actions/setup"

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  lint-format:
    name: Lint and format
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: "./.github/actions/setup"

      - name: Run lint
        run: npm run lint
      - name: Run format
        run: npm run format:check

  test:
    name: Test
    needs:
      - install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-

      - name: Run tests
        run: npm run test:ci

  build:
    name: Build
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: "./.github/actions/setup"

      - name: Run build
        run: npm run build
