name: TSFlow Release

on:
  push:
    branches:
      - main
      - alpha

env:
  HUSKY: 0

jobs:
  semantic-release:
    name: Tag and release latest version
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: "./.github/actions/setup"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
